# Please make sure to update the license_key information with the
# license key for your New Relic account.
#
newrelic:
  #
  # Update with your New Relic account license key:
  #
  license_key: 'YOUR_LICENSE_KEY_HERE'
  #
  # Set to '1' for verbose output, remove for normal output.
  # All output goes to stdout/stderr.
  #
  # verbose: 1
#
# AWS configuration.
#
aws:
  # Update with you AWS account keys:
  access_key: 'YOUR_AWS_ACCESS_KEY_HERE'
  secret_key: 'YOUR_AWS_SECRET_KEY_HERE'
  # Specify AWS regions to query for metrics
  # regions:
  #   us-east-1
#
# Agent configuration.
#
agents:
  #
  # Uncomment an agent to enable it. Set 'overview' to true to
  # enable its overview plugin (eg. EC2 Overview), displaying all
  # metrics on a single dashboard (currently only available for EC2 & EBS).
  # Note: Overview dashboards are being deprecated
  #
  # Tag filtering is available and is documented at
  # https://github.com/newrelic-platform/newrelic_aws_cloudwatch_plugin/blob/master/README.md#tag-filtering
  # 
  # An optional cloudwatch_delay attribute can be added for each agent
  # which adjusts the time window in seconds for CloudWatch querying.
  # Some of the Cloudwatch metrics are not immediately available and may 
  # require a delay before being queried.
  ec2:
    overview: false
  ebs:
    overview: false
  # elb:
  #   overview: false
  # rds:
  #   overview: false
  # sqs:
  #   overview: false
  # sns:
  #   overview: false
  # ec:
  #   overview: false
